name = "wirespeed-pagerduty-integration"
main = "src/index.ts"
compatibility_date = "2026-01-01"
workers_dev = false

[vars]
POLLING_INTERVAL_SECONDS = 15

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[[durable_objects.bindings]]
name = "CASE_WATCHER"
class_name = "CaseWatcher"

[[migrations]]
tag = "v1"
new_classes = ["CaseWatcher"]
